
fake_camera_info_node:
  ros__parameters:
    camera_fov: "92.0,76.0" 
    input_topic: camera/image_raw/compressed
    input_type: compressed
    output_topic: camera/image_raw
    output_type: raw
    camera_info_topic: camera/camera_info  # synchronized output with camera image
    frame_id: camera_link_optical

webcam_publisher_raw:
  ros__parameters:
    none: none # no parameters for this node, it just publishes raw images from the webcam

webcam_publisher:
  ros__parameters:
    input_topic: camera/image_raw/compressed
    input_type: compressed
    output_topic: camera/image_raw
    output_type: raw
    frame_id: camera_link_optical

camera_publisher_gs:
  ros__parameters:
    input_topic: camera/image_raw/compressed
    input_type: compressed
    output_topic: camera/image_raw
    output_type: raw
    frame_id: camera_link_optical